message(STATUS "I WAS HERE!!!! YOOOOHOOOOOO!!!!!")
message(STATUS "CPACK_GENERATOR: ${CPACK_GENERATOR}")

macro(unset_then_force_set)
	unset(${ARGV0})
	unset(${ARGV0} CACHE)
	set("${ARGV0}" "${ARGV1}" CACHE STRING "" FORCE)
endmacro()

if(CPACK_GENERATOR MATCHES "DEB")
	unset_then_force_set(CPACK_PACKAGING_INSTALL_PREFIX "/home/mate/Source/Test-Packaging/install")
	unset_then_force_set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/mate/Source/Test-Packaging;/usr/src/libuseful")
endif()

if(CPACK_GENERATOR MATCHES "TGZ")
	unset_then_force_set(CPACK_PACKAGING_INSTALL_PREFIX "")
	unset_then_force_set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/mate/Source/Test-Packaging;/")
endif()

#[[
message(STATUS "CPACK_SOURCE_INSTALLED_DIRECTORIES: ${CPACK_SOURCE_INSTALLED_DIRECTORIES}")
message(STATUS "CPACK_SOURCE_INSTALLED_DIRECTORIES: [Unsetting]")
unset(CPACK_SOURCE_INSTALLED_DIRECTORIES)
unset(CPACK_SOURCE_INSTALLED_DIRECTORIES CACHE)
message(STATUS "CPACK_SOURCE_INSTALLED_DIRECTORIES: [FORCE setting]")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/mate/Source/Test-Packaging;/usr/src/libuseful" CACHE STRING "" FORCE)
message(STATUS "CPACK_SOURCE_INSTALLED_DIRECTORIES: ${CPACK_SOURCE_INSTALLED_DIRECTORIES}")

unset(CPACK_PACKAGING_INSTALL_PREFIX)
set(CPACK_PACKAGING_INSTALL_PREFIX "" CACHE STRING "" FORCE)
]]