name: Linting

on:
  workflow_call:

permissions:
  contents: read

jobs:
  clang-format:
    name: ClangFormat
    runs-on: ubuntu-latest
    steps:
    - name: Pretends to run clang-format
      shell: pwsh
      run: Write-Host 'Checked if formatting was okay and all was fine!'