name: Presubmit

on: [push, pull_request]

jobs:
  formatting:
    name: Formatting
    uses: ./.github/workflows/formatting.yml
  linux:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Obtain CMake 3.25.x
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"  # use most recent 3.25.x version

    - name: Git clone repository
      uses: actions/checkout@v4

    - name: Run CMake workflow preset
      run: cmake --workflow --preset ninja-mc-ci-linux

  windows:
    needs: formatting
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Obtain CMake 3.25.x
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"  # use most recent 3.25.x version

    - name: Git clone repository
      uses: actions/checkout@v4

    - name: Run CMake workflow preset
      run: cmake --workflow --preset msbuild-ci-windows
